### ISSUE TITLE
Automatic Port Forwarding

### ISSUE THREAD

**Issue by TheUltiOne** [Jesus-QC/SecretAdmin#15]
Title says it, like Terraria's server.

**Comment by TheUltiOne** [comment]
Misclick, but also UPnP does that. I think I might make a PR for this.

**Comment by warden161** [comment]
I can do this.

**Comment by Jesus-QC** [comment]
I dont think it should be a feature since it is something not everyone needs. It can be a official module in the next release though!

**Comment by warden161** [comment]
What I was planning to do was a module but alas, discord conversation

**Comment by warden161** [comment]
I made this plugin but alas, this is a basegame feature.

I may be braindead.
EDIT: Can you close this?

**Comment by Jesus-QC** [comment]
Lmao
