### ISSUE TITLE
Doesn't work with pterodactyl

### ISSUE THREAD

**Issue by EsserGaming** [Jesus-QC/SecretAdmin#6]
The configuration process is broken and commands are really delayed. 
And some text is 🤔
![image](https://user-images.githubusercontent.com/36900138/143663915-896a059d-b683-4d31-a3d2-5440852ed35f.png)

**Comment by TheUltiOne** [comment]
@Jesus-QC fix?

**Comment by Jesus-QC** [comment]
Has been fixed.

**Comment by TheUltiOne** [comment]
thanks

**Comment by EsserGaming** [comment]
Only took a year 😏

**Comment by Jesus-QC** [comment]
> Only took a year 😏

See, AAA quality
